name: 'CI: pull request'

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pull_request_job:
    name: CI
    uses: Novolis-Platform/novolis-workflows/.github/workflows/dotnet-pull-request.yml@main
    secrets: inherit
