name: Release
on:
  release:
    types: [published]
jobs:
  ci:
    uses: Novolis-Platform/novolis-workflows/.github/workflows/dotnet-release-publish.yml@main
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    permissions:
      contents: write
